package com.exchange.order.entity;

import com.exchange.common.events.OrderSide;
import com.exchange.common.events.OrderStatus;
import com.exchange.common.events.OrderType;
import jakarta.persistence.*;

import java.math.BigDecimal;
import java.time.Instant;

/**
 * Persistent record of every order (the engine keeps books in memory; MySQL is
 * the system of record). Status transitions arrive asynchronously via the
 * "orders.status" Kafka topic -- eventual consistency by design.
 */
@Entity
@Table(name = "orders", indexes = {
        @Index(name = "idx_orders_user", columnList = "userId, createdAt"),
        @Index(name = "idx_orders_symbol_status", columnList = "symbol, status")
})
public class OrderEntity {

    @Id
    @Column(length = 36)
    private String id; // UUID, generated by this service so it's known before Kafka publish

    @Column(nullable = false)
    private Long userId;

    @Column(nullable = false, length = 10)
    private String symbol;

    @Enumerated(EnumType.STRING) @Column(nullable = false, length = 4)
    private OrderSide side;

    @Enumerated(EnumType.STRING) @Column(nullable = false, length = 6)
    private OrderType type;

    @Column(precision = 18, scale = 4)
    private BigDecimal price;

    @Column(nullable = false)
    private long quantity;

    @Column(nullable = false)
    private long filledQuantity = 0;

    @Enumerated(EnumType.STRING) @Column(nullable = false, length = 20)
    private OrderStatus status = OrderStatus.NEW;

    @Column(length = 64)
    private String rejectReason;

    @Version
    private long version; // optimistic locking: status updates may race

    @Column(nullable = false, updatable = false)
    private Instant createdAt = Instant.now();

    private Instant updatedAt;

    protected OrderEntity() {}

    public OrderEntity(String id, Long userId, String symbol, OrderSide side,
                       OrderType type, BigDecimal price, long quantity) {
        this.id = id; this.userId = userId; this.symbol = symbol;
        this.side = side; this.type = type; this.price = price; this.quantity = quantity;
    }

    public void applyStatus(OrderStatus status, long filledQuantity, String reason) {
        this.status = status;
        this.filledQuantity = filledQuantity;
        this.rejectReason = reason;
        this.updatedAt = Instant.now();
    }

    public String getId() { return id; }
    public Long getUserId() { return userId; }
    public String getSymbol() { return symbol; }
    public OrderSide getSide() { return side; }
    public OrderType getType() { return type; }
    public BigDecimal getPrice() { return price; }
    public long getQuantity() { return quantity; }
    public long getFilledQuantity() { return filledQuantity; }
    public OrderStatus getStatus() { return status; }
    public String getRejectReason() { return rejectReason; }
    public Instant getCreatedAt() { return createdAt; }
}
